FROM amazon/aws-cli

RUN yum install -y yum-utils jq ca-certificates \
    && yum-config-manager \
       --add-repo https://download.docker.com/linux/amazonlinux/docker-ce.repo \
    && yum install -y docker-ce-cli \
    && docker --version